### ISSUE TITLE
how to run in command line

### ISSUE THREAD

**Issue by parisni** [vadi2/fhir-formats#7]
hi 

i am not familiar with lua.
i did install your software with  luarocks

I then tried to run some example:

```
local to_json = require("fhirformats").to_json
to_json("xml content")

stack traceback:
	[C]: in function 'load'
	/usr/local/share/lua/5.1/xml/init.lua:129: in function </usr/local/share/lua/5.1/xml/init.lua:128>
	(tail call): ?
	/usr/local/share/lua/5.1/fhirformats.lua:572: in function 'to_json'
	hello.lua:2: in main chunk
	[C]: ?

```

**Comment by vadi2** [comment]
Try:

```lua
local to_json = require("fhirformats").to_json
print(to_json([[
<Patient xmlns='http://hl7.org/fhir'>
  <id value='examle'/>
  <active value='true'/>
</Patient>]]))
```

**Comment by parisni** [comment]
thanks.
this did not work i do no why (apparently the local breaks things)

I finally create that script:

``` lua
params = {...}
to_xml = require("fhirformats").to_xml
print(to_xml(params[1], {file = true}))
```

usage
``` bash
lua script.lua myResource.json
```

thanks for your great tool

**Comment by vadi2** [comment]
If you use it in the Lua REPL - each line is its own block, so the `local` exists for that line only. In a real Lua script/program, `local` will be fine :)

Glad it helped!

What are you hoping to use it with?

**Comment by parisni** [comment]
some tools such implementation guide ask for xml files as input. i have a bunch of json (valuesets) files and i have to transform them to xml to automatize the build of the IG

PS: i have some warnings such :

``` bash
Warning: ImplementationGuide.packageId is not a known FHIR element; won't be able to sort it properly in the XML output.
Warning: ImplementationGuide.definition is not a known FHIR element; won't be able to sort it properly in the XML output.
```

any thought how to make them quiet ?

**Comment by vadi2** [comment]
It's an important warning because in FHIR's XML, order of elements matters. Are you working with STU3?

**Comment by parisni** [comment]
I am using R4

**Comment by vadi2** [comment]
I've only generated data for STU3, haven't done an R4 version yet. Need to update the data in `src/fhir-data` - there's a script there; it might need to be updated for R4 first. Can you look into that?

**Comment by parisni** [comment]
>  Can you look into that?

does this need to update the lua script or only the json sources

**Comment by vadi2** [comment]
json sources for sure, but maybe the script too if something has changed in R4 that affects it

**Comment by parisni** [comment]
if I get trouble with my goal, i will dig into lua to upgrade that stuff to r4 soon

**Comment by vadi2** [comment]
R4 conversions are now available.
