### ISSUE TITLE
Cardinality: no JSON array if only one item given in XML

### ISSUE THREAD

**Issue by arauchberger** [vadi2/fhir-formats#8]
Hi Vadim,

is it possible that the conversion from XML to JSON has issues with the cardinality?
e.g. DocumentReference/category [0…*] is not transformed to an json-array when only one category is given in the xml.
the same problem occurs on the coding within the category.
and if i place two categories in the xml still only one is displayed in the JSON.

thanks for any feedback.

AndiY

**Comment by vadi2** [comment]
Is this using STU3?

**Comment by arauchberger** [comment]
i created my sample-xml "manually" aligned to R4. But i think this is version independent here.
please see: http://hl7.org/fhir/json.html#repeat

**Comment by arauchberger** [comment]
here is my xml:

[sample.xml.zip](https://github.com/vadi2/fhir-formats/files/5034525/sample.xml.zip)

**Comment by vadi2** [comment]
Unfortunately it is version dependant as STU3 doesn't have a category element, and R4 does - so the conversion doesn't know what datatype to use, as it only has metadata for STU3.

To fix this, R4 data would need to be generated and loaded in.
